resources:
  - allowedrepos
  - block-nodeport-services
  - containerlimits
  - containerresourceratios
  - disallowedtags
  - externalip
  - httpsonly
  - imagedigests
  - requiredlabels
  - requirednodeselectors
  - requiredprobes
  - uniqueingresshost
  - uniqueserviceselector
