apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowedRunAsUserNames
metadata:
  name: runasusername-is-not-containeradmin
spec:
  match:
    kinds:
      - apiGroups: ["","apps","batch"]
        kinds: ["Pod","Deployment","StatefulSet","ReplicationController","ReplicaSet","DaemonSet","Job"]
    namespaces:
      - "default"
  parameters:
    disallowedUserNames:
      - "ContainerAdmin"
