apiVersion: v1
kind: Pod
metadata:
  name: nanoserver-as-containeruser
spec:
  containers:
  - name: ping-loop-limits
    image: mcr.microsoft.com/windows/nanoserver:1809
    command:
      - "ping"
      - "-t"
      - "127.0.0.1"
    resources:
      limits:
        cpu: .25
        mem: 250m
  - name: ping-loop-limits-and-requests
    image: mcr.microsoft.com/windows/nanoserver:1809
    command:
      - "ping"
      - "-t"
      - "127.0.0.1"
    resources:
      limits:
        cpu: .25
        mem: 250m
      requests:
        cpu: .25
        mem: 250m
  nodeSelector:
    "kubernetes.io/os": windows