apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequirednodeselectors
  annotations:
    description: Requires Pods to have node selectors.
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredNodeSelectors
      validation:
        openAPIV3Schema:
          properties:
            nodeSelectors:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequirednodeselectors

        violation[{"msg": msg}] {
          required := input.parameters.nodeSelectors[_]
          not input.review.object.spec.nodeSelector[required]
          msg := sprintf("Pod spec must specify the following node selectors: %v", [input.parameters.nodeSelectors])
        }
